[build]
  functions = "functions/"

[[functions]]
  name = "gradio_app"
  runtime = "python"
  directory = "functions/gradio_app"
  included_files = ["functions/gradio_app/main.py", "requirements.txt"]

[dev]
  command = "python functions/gradio_app/main.py"
